### ISSUE TITLE
Result of intermediate inference similar to fake masks for unlabeled frames

### ISSUE THREAD

**Issue by DeliaZhu** [yk-pku/Two-shot-Video-Object-Segmentation#7]
I trained on my own dataset. Fake masks with random content are created for the unlabeled frames in phase 1, which is completely different from the true masks. However, in the intermediate inference, the pseudo labels generated for the unlabeled frames are very similar to the fake masks used in phase 1. I find this very strange if indeed your code does not use the fake masks of the unlabeled frames in both phase 1 and intermediate inference. I provide one true mask for labeled frames (Fig 1), one fake mask for unlabeled frames (Fig 2), and one pseudo label for unlabeled frames generated by intermediate inference (Fig 3) and I would like to hear some of your thoughts on this result.
![true_mask_for_labeled_frame](https://github.com/yk-pku/Two-shot-Video-Object-Segmentation/assets/140250147/44919739-2726-4190-847d-1affa57ef93d)
![fake_mask_for_unlabeled_frame_in_phase_1](https://github.com/yk-pku/Two-shot-Video-Object-Segmentation/assets/140250147/6f2ed46c-8f61-48aa-ad1b-793388272c57)
![pesudo_label_created_in_intermediate_inference](https://github.com/yk-pku/Two-shot-Video-Object-Segmentation/assets/140250147/7db8780b-87d0-4178-96c3-4de50cc6557d)

**Comment by yk-pku** [comment]
I did not know what the format of your own dataset was. The codes are developed based on YouTube-VOS and DAVIS, some parameters such as 'selector' and the predefined 'mask_dir' make sure only two labeled frames per video are available without changing any structures of the original datasets. But I guess your problem is due to the access to the fake masks during the intermediate inference, because you need to make sure the mask_dir only contains GTs.

**Comment by DeliaZhu** [comment]
Well, I removed the fake masks, ran the intermediate inference, and got the normal results. Thanks! If convenient, hope you can add some tips on training on our own dataset in the documentation.

**Comment by yk-pku** [comment]
Ok, when I have time.
